# Generated by Django 5.1.5 on 2025-02-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Plot', models.CharField(max_length=400)),
                ('Director', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=200)),
                ('Poster', models.CharField(max_length=200)),
            ],
        ),
    ]
