# Generated by Django 5.1.5 on 2025-02-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Year',
            field=models.CharField(default='0', max_length=4),
            preserve_default=False,
        ),
    ]
