# Generated by Django 5.1.5 on 2025-02-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_order_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
