# Generated by Django 5.1.4 on 2025-02-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_remove_review_body_remove_review_user_review_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
